# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:14
from __future__ import unicode_literals

import Tagent.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent.validators.validate_city])),
                ('state', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent.validators.validate_state])),
                ('landmark', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent.validators.validate_landmark])),
                ('pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentReferal',
            fields=[
                ('referal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, validators=[Tagent.validators.validate_name])),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, validators=[Tagent.validators.validate_mobile_number])),
                ('phone_number', models.CharField(max_length=20, validators=[Tagent.validators.validate_phone_number])),
                ('email_id', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent.validators.validate_city])),
                ('state', models.CharField(blank=True, max_length=20, null=True, validators=[Tagent.validators.validate_state])),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('propert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent.ContactInfo')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[Tagent.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[Tagent.validators.validate_last_name])),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50, validators=[Tagent.validators.validate_education])),
                ('company_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100, validators=[Tagent.validators.validate_specialization])),
                ('experience', models.IntegerField()),
                ('agent_notes', models.TextField()),
                ('property_type', models.ManyToManyField(to='Tagent.PropertyType')),
            ],
            bases=('Tagent.contactinfo',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Tagent.ContactInfo')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[Tagent.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[Tagent.validators.validate_last_name])),
            ],
            bases=('Tagent.contactinfo',),
        ),
        migrations.AddField(
            model_name='location',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tagent.Agent'),
        ),
        migrations.AddField(
            model_name='agentreferal',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tagent.Agent'),
        ),
        migrations.AddField(
            model_name='address',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tagent.Agent'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tagent.Customer'),
        ),
    ]
